"""CVRP mechanism-family aliases used by problem-owned evidence reviews."""

from __future__ import annotations

CONSTRUCTION_SEED_PORTFOLIO_ALIASES = (
    "construction_seed_portfolio",
    "construction_seed",
    "seed_portfolio",
    "initial_solution",
    "rotated_sweep_seed_tournament",
    "sweep_seed_tournament",
    "rotated_sweep_seed",
    "sweep_seed",
    "sweep_construction",
    "savings_seed_selection_probe",
    "savings_seed_selection",
    "same_route_count_savings_variant_selection",
    "savings_variant_selection",
    "savings_seed_portfolio",
    "savings_seed",
    "cw_sweep_seed_baseline_selector",
    "short_horizon_seed_trajectory_selector",
    "short_horizon_seed_trajectory_selector_v2",
    "seed_trajectory_selector",
    "post_trajectory_seed_selector",
    "savings_construction",
    "clarke_wright_savings",
    "clarke_wright",
    "cw_savings",
    "construction",
)

BOUNDED_LOCAL_SEARCH_VARIANT_ALIASES = (
    "bounded_local_search_variant",
    "bounded_local_search",
    "local_search",
    "deadline_aware_local_search",
    "bounded_2node_cross_exchange",
    "two_node_cross_exchange",
    "2node_cross_exchange",
    "cross_exchange",
    "intra_route_or_opt_reinsert",
    "or_opt_reinsert",
    "same_route_or_opt_reinsertion",
    "intra_route_block_reinsert",
    "bounded_same_route_or_opt_reinsertion",
    "alns_vns_intra_route_block_reinsert",
    "bounded_intra_route_3opt",
    "bounded_intra_route_three_opt",
    "intra_route_3opt",
    "intra_route_three_opt",
    "bounded_ejection_chain_relocate",
    "ejection_chain_relocate",
    "neighbor_list_vns_filter",
    "frozen_safe_neighbor_list_vns_filter",
    "neighbor_list_filter",
    "vns_candidate_list_filter",
    "candidate_list_vns_filter",
    "nearest_neighbor_vns_filter",
    "two_step_ejection_chain_relocation",
    "ejection_chain",
    "3opt",
    "three_opt",
    "segment_swap",
    "route_pair_exchange",
    "two_opt_intra_bounded",
)

DESTROY_REPAIR_SELECTION_ALIASES = (
    "destroy_repair_selection",
    "destroy_repair",
    "angular_sector_removal",
    "angular_sector",
    "radial_string_removal",
    "farthest_noise_related_removal",
    "polar_sweep_destroy_repair",
    "polar_sweep",
    "route_fragment_recombination_repair",
    "fragment_recombination_repair",
    "route_fragment_recombination",
    "adjacency_pair_removal_repair",
    "adjacency_pair_removal",
    "load_compatible_ruin_recreate",
    "load_compatible_ruin",
    "capacity_tightness_removal",
    "capacity_tightness",
    "removal",
    "repair",
    "lookahead_insertion_cost_repair",
    "lookahead_insertion_cost_repair_v2",
    "insertion_cost_lookahead",
    "paired_insertion_cost_lookahead",
    "route_pair_overlap_removal",
    "route_pair_overlap_removal_protected",
    "route_pair_overlap_removal_protected_followup",
    "route_pair_overlap",
    "regret_insertion",
    "insertion",
    "shaw_removal",
    "worst_removal",
)

SCHEDULER_DESTROY_SIZE_POLICY_ALIASES = (
    "scheduler_destroy_size_policy",
    "stagnation_adaptive_destroy_size_schedule",
    "operator_pair_destroy_size_bands",
    "adaptive_destroy_size_schedule",
    "adaptive_destroy_size",
    "destroy_size_schedule",
    "destroy_size_policy",
    "alns_destroy_size_schedule",
    "alns_destroy_size",
    "q_schedule",
    "adaptive_q",
    "destroy_magnitude_schedule",
    "scheduler_policy",
)

ACCEPTANCE_OR_ADAPTIVE_WEIGHTING_ALIASES = (
    "acceptance_or_adaptive_weighting",
    "post_repair_effect_credit_weighting",
    "post_repair_credit_weighting",
    "operator_credit_weighting",
    "operator_pair_credit_weighting",
    "adaptive_weighting",
    "adaptive_weights",
    "operator_weighting",
    "credit_weighting",
    "rank_gap",
    "route_pressure",
    "acceptance",
)

SCHEDULER_RUNTIME_ALLOCATION_ALIASES = (
    "scheduler_runtime_allocation",
    "adaptive_embedded_vns_runtime_allocation",
    "embedded_vns_runtime_allocation",
    "runtime_allocation",
    "embedded_vns_share",
)

CVRP_SUCCESSOR_FAMILY_ALIASES = {
    "scheduler_destroy_size_policy": SCHEDULER_DESTROY_SIZE_POLICY_ALIASES,
    "acceptance_or_adaptive_weighting": ACCEPTANCE_OR_ADAPTIVE_WEIGHTING_ALIASES,
    "scheduler_runtime_allocation": SCHEDULER_RUNTIME_ALLOCATION_ALIASES,
    "construction_seed_portfolio": CONSTRUCTION_SEED_PORTFOLIO_ALIASES,
    "bounded_local_search_variant": BOUNDED_LOCAL_SEARCH_VARIANT_ALIASES,
    "destroy_repair_selection": DESTROY_REPAIR_SELECTION_ALIASES,
}
