"""CVRP-owned solver-design provider support modules."""

from scion.problems.cvrp.solver_design.manifest import (
    ACTIVE_SOLVER_DESIGN_PACKAGE,
    BROAD_SCOPE_TERMS,
    SOLVER_DESIGN_API_MANIFEST_FILES,
    SOLVER_DESIGN_INTEGRATION_FULL_FILES,
    SOLVER_DESIGN_INTEGRATION_SUMMARY_FILES,
)

__all__ = [
    "ACTIVE_SOLVER_DESIGN_PACKAGE",
    "BROAD_SCOPE_TERMS",
    "SOLVER_DESIGN_API_MANIFEST_FILES",
    "SOLVER_DESIGN_INTEGRATION_FULL_FILES",
    "SOLVER_DESIGN_INTEGRATION_SUMMARY_FILES",
]
