
"""Shared imports/constants for APS session mixins."""
from __future__ import annotations

import json
import signal
import time
import uuid
from dataclasses import replace
from pathlib import Path
from typing import Any, Callable, Mapping, Protocol

from scion.core.models import HypothesisProposal, PatchProposal
from scion.proposal.engine import ProposalValidationError
from scion.proposal.agentic_artifacts import (
    AgenticSessionStore,
    FileAgenticSessionArtifactStore,
    compute_agentic_idempotency_key,
    ensure_agentic_output_audit_metadata,
    inspect_agentic_session_artifact,
    resume_from_artifact,
    validate_agentic_session_artifact,
    _agentic_output_artifact,
    _agentic_transcript_artifact,
    _champion_version,
    _champion_weight_revision,
    _compact_transcript,
    _load_artifact_payload,
    _proposal_payload,
    _tool_call_fingerprint,
    _tool_budget_used_payload,
    _tool_loop_config_payload,
    _transcript_digest,
)
from scion.proposal.agentic_models import (
    AGENTIC_SESSION_SCHEMA_VERSION,
    AgenticEvidenceRef,
    AgenticFailureCategory,
    AgenticProposalOutput,
    AgenticProposalPhase,
    AgenticProposalRequest,
    AgenticProposalSessionState,
    AgenticProposalStatus,
    AgenticSessionArtifactStore,
    AgenticTerminationReason,
    AgenticTranscriptEvent,
    AgenticToolLoopConfig,
    CreativeProposalLike,
)
from scion.proposal.agentic_code_context import (
    _code_context_tool_summary,
    _code_observation_prompt_payload,
    _code_prompt_observations,
    _code_timeout_retry_context,
    _is_code_generation_timeout,
    _observation_prompt_payload,
    _with_code_scope_control,
)
from scion.proposal.agentic_diagnostics import _research_diagnosis_from_observations
from scion.proposal.agentic_failure_classification import (
    _hypothesis_semantic_retry_rejection_payload,
    _failure_ledger_payload,
    _normalized_structured_rejection,
    _patch_premise_rejection,
    _patch_self_reported_unresolved_issue,
    _preview_failure_category,
    _record_failure_ledger_entry,
    _rejection_termination_reason,
    _structured_output_failure_category,
    _terminal_failure_category,
)
from scion.proposal.agentic_grounding import (
    _SOLVER_DESIGN_FILE_DISCOVERY_TOOLS,
    _SOLVER_DESIGN_GROUNDING_TOOLS,
    _active_solver_mechanism_evidence_for_code_context,
    _compact_active_solver_observation_for_budget,
    _context_requires_solver_design_grounding,
    _fallback_required_context_tool_names,
    _has_active_solver_embedded_call_graph,
    _has_successful_solver_call_graph_grounding,
    _is_solver_design_hypothesis,
    _missing_solver_design_grounding_error,
    _required_context_tool_names,
    _run_required_context_preface as _run_required_context_preface_tools,
    _run_selected_surface_observation_tool as _run_selected_surface_context_tool,
    _run_solver_design_grounding_tools as _run_solver_design_grounding_context_tools,
    _solver_design_target_file_read_args,
)
from scion.proposal.agentic_planner_policy import (
    _available_compact_feedback_tools as _planner_available_compact_feedback_tools,
    _missing_planner_context_error as _planner_missing_context_error,
    _missing_required_context_error as _policy_missing_required_context_error,
    _planner_context_satisfied as _planner_policy_context_satisfied,
    _planner_observation_requires_fallback as _policy_planner_observation_requires_fallback,
    _pop_deferred_code_phase_tool_call,
    _push_deferred_code_phase_tool_call,
    _should_defer_diagnosis_tool_to_code_phase,
    _solver_design_planner_algorithm_file_read_budget_exhausted,
)
from scion.proposal.mechanism_novelty import MechanismNoveltyGate
from scion.proposal.agentic_preview import (
    AgenticSelfCheck,
    _algorithm_smoke_failure_detail,
    _compact_algorithm_smoke_observation,
    _compact_contract_preview_observation,
    _compact_self_check_preview_observation,
    _latest_preview_failure_detail,
    _minimal_self_check_preview_observation,
    _preview_observation_passed,
    _preview_skip_is_agentic_budget_control,
    _self_check_failure_detail,
    _self_check_from_previews,
    _self_check_required,
)
from scion.proposal.agentic_session_budget import (
    _code_phase_budget_reserved as _code_phase_budget_reserved_for_config,
    _diagnosis_budget_reserved as _diagnosis_budget_reserved_for_config,
    _diagnosis_feedback_budget_reserved as _diagnosis_feedback_budget_reserved_for_config,
    _minimum_budgeted_observation_chars,
    _observation_budget_exhausted as _observation_budget_exhausted_for_config,
    _optional_surface_read_budget_floor as _optional_surface_read_budget_floor_for_config,
    _remaining_observation_chars as _remaining_observation_chars_for_config,
    _remaining_tool_calls as _remaining_tool_calls_for_config,
    _remaining_tool_steps as _remaining_tool_steps_for_config,
    _self_check_observation_reserve_chars as _self_check_observation_reserve_chars_for_config,
    _self_check_step_reserve as _self_check_step_reserve_for_config,
    _self_check_tool_call_reserve as _self_check_tool_call_reserve_for_config,
    _should_deny_optional_tool_for_budget as _should_deny_optional_tool_for_budget_config,
)
from scion.proposal.agentic_session_feedback import (
    _compact_feedback_observation_for_budget,
    _feedback_query_args,
    _has_feedback_screening_history,
    _observation_satisfies_compact_requirement,
)
from scion.proposal.agentic_session_tools import (
    _APS_CODE_MODULE_SURFACE_READ_CODE_CHARS,
    _APS_CODE_SURFACE_READ_CODE_CHARS,
    _APS_SURFACE_READ_CODE_CHARS,
    _algorithm_file_path_guidance,
    _budgeted_tool_args,
    _filter_code_phase_tool_names,
    _filter_model_facing_tool_names,
    _has_code_phase_surface_read,
    _has_successful_code_phase_reusable_observation,
    _has_successful_reusable_observation,
    _has_successful_surface_read,
    _has_successful_tool,
    _is_solver_design_algorithm_target,
    _is_solver_design_support_module_target,
    _observation_selection_payload,
    _recommended_algorithm_file_path,
    _solver_design_code_algorithm_file_read_budget_exhausted,
    _surface_names_from_observations,
)
from scion.proposal.agentic_utils import (
    _drop_empty_dict,
    _enum_value,
    _json_size,
    _limit_string,
    _sanitize_agentic_value,
)
from scion.proposal.llm_client import LLMFormatError, LLMRetryExhaustedError, LLMTimeoutError
from scion.proposal.prompt_manifest import build_api_visible_prompt_manifest, stable_digest
from scion.proposal.tools import (
    ProposalExposureLevel,
    ProposalObservation,
    ProposalTaint,
    ProposalToolContext,
    ProposalToolFailureCode,
    ProposalToolPermission,
    ProposalToolRegistry,
    _active_boundary_novelty_requirements,
)
from scion.proposal.agentic_session_observations import (
    _authoritative_preview_observations,
    _deduplicate_observation_if_already_read,
    _evidence_from_observations,
    _hypothesis_prompt_observations,
    _is_authoritative_self_check_preview_call,
    _next_prompt_manifest_index,
    _patch_payload_for_preview,
)
from scion.proposal.agentic_session_timeouts import (
    _ALGORITHM_SMOKE_TOOL_TIMEOUT_SEC,
    _CONTRACT_PREVIEW_TOOL_TIMEOUT_SEC,
    _FINAL_PREVIEW_WALL_TIME_RESERVE_SEC,
    _ProposalToolTimeout,
    _can_use_signal_timeout,
    _preview_tool_timeout_sec,
)

_MAX_HYPOTHESIS_SEMANTIC_RETRIES = 1
_APS_TARGET_ALGORITHM_FILE_READ_CHARS = 24000
_SELF_CHECK_PREVIEW_OBSERVATION_BUDGET_CHARS = 24000
_MECHANISM_NOVELTY_GATE = MechanismNoveltyGate()

# Transitional explicit export set for APS mixins and the legacy facade.
# Keep this list deliberate: adding a dependency here means the split modules
# are sharing it as session infrastructure, not incidentally leaking globals.
__all__ = (
    "AGENTIC_SESSION_SCHEMA_VERSION",
    "AgenticEvidenceRef",
    "AgenticFailureCategory",
    "AgenticProposalOutput",
    "AgenticProposalPhase",
    "AgenticProposalRequest",
    "AgenticProposalSessionState",
    "AgenticProposalStatus",
    "AgenticSelfCheck",
    "AgenticSessionArtifactStore",
    "AgenticSessionStore",
    "AgenticTerminationReason",
    "AgenticToolLoopConfig",
    "AgenticTranscriptEvent",
    "Any",
    "Callable",
    "CreativeProposalLike",
    "FileAgenticSessionArtifactStore",
    "HypothesisProposal",
    "LLMFormatError",
    "LLMRetryExhaustedError",
    "LLMTimeoutError",
    "Mapping",
    "MechanismNoveltyGate",
    "PatchProposal",
    "Path",
    "ProposalExposureLevel",
    "ProposalObservation",
    "ProposalTaint",
    "ProposalToolContext",
    "ProposalToolFailureCode",
    "ProposalToolPermission",
    "ProposalToolRegistry",
    "ProposalValidationError",
    "Protocol",
    "_ALGORITHM_SMOKE_TOOL_TIMEOUT_SEC",
    "_APS_CODE_MODULE_SURFACE_READ_CODE_CHARS",
    "_APS_CODE_SURFACE_READ_CODE_CHARS",
    "_APS_SURFACE_READ_CODE_CHARS",
    "_APS_TARGET_ALGORITHM_FILE_READ_CHARS",
    "_CONTRACT_PREVIEW_TOOL_TIMEOUT_SEC",
    "_FINAL_PREVIEW_WALL_TIME_RESERVE_SEC",
    "_MAX_HYPOTHESIS_SEMANTIC_RETRIES",
    "_MECHANISM_NOVELTY_GATE",
    "_ProposalToolTimeout",
    "_SELF_CHECK_PREVIEW_OBSERVATION_BUDGET_CHARS",
    "_SOLVER_DESIGN_FILE_DISCOVERY_TOOLS",
    "_SOLVER_DESIGN_GROUNDING_TOOLS",
    "_active_boundary_novelty_requirements",
    "_active_solver_mechanism_evidence_for_code_context",
    "_agentic_output_artifact",
    "_agentic_transcript_artifact",
    "_algorithm_file_path_guidance",
    "_algorithm_smoke_failure_detail",
    "_authoritative_preview_observations",
    "_budgeted_tool_args",
    "_can_use_signal_timeout",
    "_champion_version",
    "_champion_weight_revision",
    "_code_context_tool_summary",
    "_code_observation_prompt_payload",
    "_code_phase_budget_reserved_for_config",
    "_code_prompt_observations",
    "_code_timeout_retry_context",
    "_compact_active_solver_observation_for_budget",
    "_compact_algorithm_smoke_observation",
    "_compact_contract_preview_observation",
    "_compact_feedback_observation_for_budget",
    "_compact_self_check_preview_observation",
    "_compact_transcript",
    "_context_requires_solver_design_grounding",
    "_deduplicate_observation_if_already_read",
    "_diagnosis_budget_reserved_for_config",
    "_diagnosis_feedback_budget_reserved_for_config",
    "_drop_empty_dict",
    "_enum_value",
    "_evidence_from_observations",
    "_failure_ledger_payload",
    "_fallback_required_context_tool_names",
    "_feedback_query_args",
    "_filter_code_phase_tool_names",
    "_filter_model_facing_tool_names",
    "_has_active_solver_embedded_call_graph",
    "_has_code_phase_surface_read",
    "_has_feedback_screening_history",
    "_has_successful_code_phase_reusable_observation",
    "_has_successful_reusable_observation",
    "_has_successful_solver_call_graph_grounding",
    "_has_successful_surface_read",
    "_has_successful_tool",
    "_hypothesis_prompt_observations",
    "_hypothesis_semantic_retry_rejection_payload",
    "_is_authoritative_self_check_preview_call",
    "_is_code_generation_timeout",
    "_is_solver_design_algorithm_target",
    "_is_solver_design_hypothesis",
    "_is_solver_design_support_module_target",
    "_json_size",
    "_latest_preview_failure_detail",
    "_limit_string",
    "_load_artifact_payload",
    "_minimal_self_check_preview_observation",
    "_minimum_budgeted_observation_chars",
    "_missing_solver_design_grounding_error",
    "_next_prompt_manifest_index",
    "_normalized_structured_rejection",
    "_observation_budget_exhausted_for_config",
    "_observation_prompt_payload",
    "_observation_satisfies_compact_requirement",
    "_observation_selection_payload",
    "_optional_surface_read_budget_floor_for_config",
    "_patch_payload_for_preview",
    "_patch_premise_rejection",
    "_patch_self_reported_unresolved_issue",
    "_planner_available_compact_feedback_tools",
    "_planner_missing_context_error",
    "_planner_policy_context_satisfied",
    "_policy_missing_required_context_error",
    "_policy_planner_observation_requires_fallback",
    "_pop_deferred_code_phase_tool_call",
    "_preview_failure_category",
    "_preview_observation_passed",
    "_preview_skip_is_agentic_budget_control",
    "_preview_tool_timeout_sec",
    "_proposal_payload",
    "_push_deferred_code_phase_tool_call",
    "_recommended_algorithm_file_path",
    "_record_failure_ledger_entry",
    "_rejection_termination_reason",
    "_remaining_observation_chars_for_config",
    "_remaining_tool_calls_for_config",
    "_remaining_tool_steps_for_config",
    "_required_context_tool_names",
    "_research_diagnosis_from_observations",
    "_run_required_context_preface_tools",
    "_run_selected_surface_context_tool",
    "_run_solver_design_grounding_context_tools",
    "_sanitize_agentic_value",
    "_self_check_failure_detail",
    "_self_check_from_previews",
    "_self_check_observation_reserve_chars_for_config",
    "_self_check_required",
    "_self_check_step_reserve_for_config",
    "_self_check_tool_call_reserve_for_config",
    "_should_defer_diagnosis_tool_to_code_phase",
    "_should_deny_optional_tool_for_budget_config",
    "_solver_design_code_algorithm_file_read_budget_exhausted",
    "_solver_design_planner_algorithm_file_read_budget_exhausted",
    "_solver_design_target_file_read_args",
    "_structured_output_failure_category",
    "_surface_names_from_observations",
    "_terminal_failure_category",
    "_tool_budget_used_payload",
    "_tool_call_fingerprint",
    "_tool_loop_config_payload",
    "_transcript_digest",
    "_with_code_scope_control",
    "build_api_visible_prompt_manifest",
    "compute_agentic_idempotency_key",
    "ensure_agentic_output_audit_metadata",
    "inspect_agentic_session_artifact",
    "json",
    "replace",
    "resume_from_artifact",
    "signal",
    "stable_digest",
    "time",
    "uuid",
    "validate_agentic_session_artifact",
)
