"""Backward-compatible facade for the modular LLMClient implementation."""
from __future__ import annotations

from scion.proposal.llm.client import LLMClient
from scion.proposal.llm.config import (
    _ANTHROPIC_MODEL_PREFIXES,
    _CODE_REQUEST_KINDS,
    _DEFAULT_BASE_URL,
    _DEFAULT_CODE_TIMEOUT_SEC,
    _DEFAULT_MODEL,
    _DEFAULT_TIMEOUT_SEC,
    _DEEPSEEK_MAX_ALIASES,
    _DEEPSEEK_MODEL_PREFIXES,
    _TOOL_REQUEST_KIND_BY_NAME,
    _env_float,
    _is_deepseek_model,
    _is_openai_model,
    _normalize_model_alias,
    _normalize_request_kind,
    _request_kind_env_key,
)
from scion.proposal.llm.errors import (
    LLMAuthError,
    LLMBalanceError,
    LLMError,
    LLMFormatError,
    LLMProviderError,
    LLMRateLimitError,
    LLMTimeoutError,
    LLMTransportError,
    _is_timeout_error_text,
    _is_transient_provider_error,
    _masked_hard_timeout_error,
    _parse_retry_after,
    is_llm_infra_error,
)
from scion.proposal.llm.timeout import _llm_hard_timeout

__all__ = [
    "LLMClient",
    "LLMAuthError",
    "LLMBalanceError",
    "LLMError",
    "LLMFormatError",
    "LLMProviderError",
    "LLMRateLimitError",
    "LLMTimeoutError",
    "LLMTransportError",
    "_ANTHROPIC_MODEL_PREFIXES",
    "_CODE_REQUEST_KINDS",
    "_DEFAULT_BASE_URL",
    "_DEFAULT_CODE_TIMEOUT_SEC",
    "_DEFAULT_MODEL",
    "_DEFAULT_TIMEOUT_SEC",
    "_DEEPSEEK_MAX_ALIASES",
    "_DEEPSEEK_MODEL_PREFIXES",
    "_TOOL_REQUEST_KIND_BY_NAME",
    "_env_float",
    "_is_deepseek_model",
    "_is_openai_model",
    "_is_timeout_error_text",
    "_is_transient_provider_error",
    "_llm_hard_timeout",
    "_masked_hard_timeout_error",
    "_normalize_model_alias",
    "_normalize_request_kind",
    "_parse_retry_after",
    "_request_kind_env_key",
    "is_llm_infra_error",
]
