"""Backward-compatible facade for the modular LLMClient implementation."""
from __future__ import annotations

import time

from scion.proposal.llm.client import LLMClient
from scion.proposal.llm.config import (
    _ANTHROPIC_MODEL_PREFIXES,
    LLM_TRANSIENT_API_ERROR_CATEGORY,
    MAX_MAX_TOKENS,
    MAX_TRUNCATION_RETRIES,
    _BACKOFF_DELAYS,
    _CODE_REQUEST_KINDS,
    _DEFAULT_BASE_URL,
    _DEFAULT_CODE_MAX_RETRIES,
    _DEFAULT_CODE_TIMEOUT_SEC,
    _DEFAULT_MAX_RETRIES,
    _DEFAULT_MAX_TOKENS,
    _DEFAULT_MODEL,
    _DEFAULT_SDK_MAX_RETRIES,
    _DEFAULT_TIMEOUT_SEC,
    _DEFAULT_TRANSIENT_PROVIDER_MAX_RETRIES,
    _DEEPSEEK_MAX_ALIASES,
    _DEEPSEEK_MODEL_PREFIXES,
    _TOOL_REQUEST_KIND_BY_NAME,
    _env_float,
    _env_int,
    _is_deepseek_model,
    _is_openai_model,
    _normalize_model_alias,
    _normalize_request_kind,
    _request_kind_env_key,
)
from scion.proposal.llm.errors import (
    LLMBalanceError,
    LLMError,
    LLMFormatError,
    LLMRateLimitError,
    LLMRetryExhaustedError,
    LLMTimeoutError,
    LLMTransientProviderError,
    _is_timeout_error_text,
    _is_transient_provider_error,
    _masked_hard_timeout_error,
    _parse_retry_after,
    _retry_exhausted_failure_category,
    _transient_retry_exhausted_error,
    is_llm_transient_api_error,
)
from scion.proposal.llm.timeout import _llm_hard_timeout

__all__ = [
    "LLMClient",
    "LLM_TRANSIENT_API_ERROR_CATEGORY",
    "LLMBalanceError",
    "LLMError",
    "LLMFormatError",
    "LLMRateLimitError",
    "LLMRetryExhaustedError",
    "LLMTimeoutError",
    "LLMTransientProviderError",
    "MAX_MAX_TOKENS",
    "MAX_TRUNCATION_RETRIES",
    "_ANTHROPIC_MODEL_PREFIXES",
    "_BACKOFF_DELAYS",
    "_CODE_REQUEST_KINDS",
    "_DEFAULT_BASE_URL",
    "_DEFAULT_CODE_MAX_RETRIES",
    "_DEFAULT_CODE_TIMEOUT_SEC",
    "_DEFAULT_MAX_RETRIES",
    "_DEFAULT_MAX_TOKENS",
    "_DEFAULT_MODEL",
    "_DEFAULT_SDK_MAX_RETRIES",
    "_DEFAULT_TIMEOUT_SEC",
    "_DEFAULT_TRANSIENT_PROVIDER_MAX_RETRIES",
    "_DEEPSEEK_MAX_ALIASES",
    "_DEEPSEEK_MODEL_PREFIXES",
    "_TOOL_REQUEST_KIND_BY_NAME",
    "_env_float",
    "_env_int",
    "_is_deepseek_model",
    "_is_openai_model",
    "_is_timeout_error_text",
    "_is_transient_provider_error",
    "_llm_hard_timeout",
    "_masked_hard_timeout_error",
    "_normalize_model_alias",
    "_normalize_request_kind",
    "_parse_retry_after",
    "_request_kind_env_key",
    "_retry_exhausted_failure_category",
    "_transient_retry_exhausted_error",
    "is_llm_transient_api_error",
    "time",
]
