"""Filesystem and canonical-byte primitives shared by CVRP F1 modules."""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import shutil
import stat
from typing import Any, Mapping, Sequence
import uuid

from scion.problems.cvrp.evidence.f1_contract import (
    CvrpF1Error,
    _GENERATED_SUFFIXES,
)


def _inventory(
    root: Path, *, allow_generated_exclusion: bool = False
) -> tuple[tuple[str, str], ...]:
    resolved = root.resolve(strict=True)
    rows: list[tuple[str, str]] = []
    for path in sorted(resolved.rglob("*"), key=lambda item: item.as_posix()):
        relative = path.relative_to(resolved)
        if path.is_symlink():
            raise CvrpF1Error(f"F1 inventory rejects symlink: {relative}")
        generated = (
            "__pycache__" in relative.parts or path.suffix in _GENERATED_SUFFIXES
        )
        if generated:
            if allow_generated_exclusion:
                continue
            raise CvrpF1Error(f"F1 inventory contains generated bytecode: {relative}")
        if path.is_dir():
            continue
        if not path.is_file():
            raise CvrpF1Error(f"F1 inventory rejects non-regular entry: {relative}")
        rows.append((relative.as_posix(), _sha256_file(path)))
    return tuple(rows)


def _copy_inventory(
    source: Path, target: Path, inventory: Sequence[tuple[str, str]]
) -> None:
    for relative, expected in inventory:
        content = _capture_regular(source / relative, label=f"source {relative}")
        if _sha256_bytes(content) != expected:
            raise CvrpF1Error(f"F1 source inventory drift: {relative}")
        _write_exclusive(target / relative, content)


def _inventory_payload(inventory: Sequence[tuple[str, str]]) -> list[dict[str, str]]:
    return [{"path": path, "sha256": digest} for path, digest in inventory]


def _git_inventory_payload(
    inventory: Sequence[tuple[str, str]],
) -> list[dict[str, str]]:
    return [{"path": path, "git_blob_sha1": digest} for path, digest in inventory]


def _inventory_sha256(inventory: Sequence[tuple[str, str]]) -> str:
    return _canonical_sha256(_inventory_payload(inventory))


def _capture_regular(path: Path, *, label: str) -> bytes:
    absolute = path.expanduser().absolute()
    _assert_no_symlink_components(absolute, label=label)
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    descriptor = os.open(absolute, flags)
    try:
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode):
            raise CvrpF1Error(f"F1 {label} is not a regular file")
        chunks = []
        while True:
            chunk = os.read(descriptor, 1024 * 1024)
            if not chunk:
                break
            chunks.append(chunk)
        after = os.fstat(descriptor)
    finally:
        os.close(descriptor)
    signature = ("st_dev", "st_ino", "st_size", "st_mtime_ns", "st_ctime_ns")
    if any(getattr(before, name) != getattr(after, name) for name in signature):
        raise CvrpF1Error(f"F1 {label} changed during capture")
    content = b"".join(chunks)
    if len(content) != before.st_size:
        raise CvrpF1Error(f"F1 {label} size drift")
    return content


def _safe_source_file(root: Path, relative: Path) -> Path:
    if relative.is_absolute() or ".." in relative.parts or not relative.parts:
        raise CvrpF1Error(f"F1 unsafe relative source path: {relative}")
    current = root.resolve(strict=True)
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            raise CvrpF1Error(f"F1 source path contains symlink: {relative}")
    resolved = current.resolve(strict=True)
    try:
        resolved.relative_to(root.resolve(strict=True))
    except ValueError as exc:
        raise CvrpF1Error(f"F1 source path escapes root: {relative}") from exc
    if not resolved.is_file():
        raise CvrpF1Error(f"F1 source path is not a regular file: {relative}")
    return resolved


def _assert_no_symlink_components(path: Path, *, label: str) -> None:
    current = Path(path.anchor)
    for part in path.parts[1:]:
        current /= part
        try:
            mode = current.lstat().st_mode
        except FileNotFoundError as exc:
            raise CvrpF1Error(f"F1 {label} does not exist: {path}") from exc
        if stat.S_ISLNK(mode):
            raise CvrpF1Error(f"F1 {label} contains symlink: {current}")


def _make_read_only(root: Path) -> None:
    for path in sorted(root.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        if path.is_file():
            path.chmod(0o444)
        elif path.is_dir():
            path.chmod(0o555)
    root.chmod(0o555)


def _assert_read_only(root: Path) -> None:
    if stat.S_IMODE(root.stat().st_mode) != 0o555:
        raise CvrpF1Error(f"F1 sealed root mode drift: {root}")
    for path in root.rglob("*"):
        expected = 0o555 if path.is_dir() else 0o444
        if stat.S_IMODE(path.stat().st_mode) != expected:
            raise CvrpF1Error(f"F1 sealed path mode drift: {path}")


def _assert_read_only_file(path: Path) -> None:
    if path.is_symlink() or not path.is_file():
        raise CvrpF1Error(f"F1 sealed file is not regular: {path}")
    if stat.S_IMODE(path.stat().st_mode) != 0o444:
        raise CvrpF1Error(f"F1 sealed file mode drift: {path}")


def _create_absent_root(value: str | Path) -> Path:
    path = Path(value).expanduser().resolve(strict=False)
    if path.exists() or path.is_symlink():
        raise CvrpF1Error(f"F1 output root must be absent: {path}")
    path.mkdir(parents=True)
    return path.resolve(strict=True)


def _reject_nested(output: Path, protected: Sequence[Path]) -> None:
    for root in protected:
        try:
            output.relative_to(root.resolve(strict=True))
        except ValueError:
            continue
        raise CvrpF1Error(f"F1 output root is nested in protected source: {root}")


def _remove_tree(path: Path, *, root: Path) -> None:
    if not path.exists():
        return
    resolved = path.resolve(strict=True)
    try:
        resolved.relative_to(root.resolve(strict=True))
    except ValueError as exc:
        raise CvrpF1Error(f"F1 refuses to remove outside output root: {path}") from exc
    shutil.rmtree(resolved)


def _write_exclusive(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("xb") as handle:
        handle.write(content)
        handle.flush()
        os.fsync(handle.fileno())


def _create_exclusive_empty(path: Path) -> None:
    _write_exclusive(path, b"")


def _publish_bytes_no_replace(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.parent / f".{path.name}.{uuid.uuid4().hex}.tmp"
    try:
        _write_exclusive(temp, content)
        os.link(temp, path, follow_symlinks=False)
        temp.unlink()
        _fsync_directory(path.parent)
    finally:
        try:
            temp.unlink()
        except FileNotFoundError:
            pass


def _publish_json_no_replace(path: Path, payload: Mapping[str, Any]) -> None:
    _publish_bytes_no_replace(path, _canonical_pretty_bytes(payload))


def _fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _file_evidence(path: Path) -> dict[str, Any]:
    if path.is_symlink() or not path.is_file():
        return {"status": "missing", "reason": "not_regular_file"}
    return {
        "status": "present",
        "path": path.name,
        "bytes": path.stat().st_size,
        "sha256": _sha256_file(path),
    }


def _load_object(path: Path, *, label: str) -> dict[str, Any]:
    try:
        payload = json.loads(
            path.read_text(encoding="utf-8"), parse_constant=_reject_constant
        )
    except (OSError, json.JSONDecodeError) as exc:
        raise CvrpF1Error(f"F1 {label} is invalid JSON") from exc
    if not isinstance(payload, dict):
        raise CvrpF1Error(f"F1 {label} must be a JSON object")
    return payload


def _reject_constant(value: str) -> None:
    raise ValueError(f"non-finite JSON constant: {value}")


def _require_hash(path: Path, expected: str, label: str) -> None:
    if path.is_symlink() or not path.is_file() or _sha256_file(path) != expected:
        raise CvrpF1Error(f"F1 {label} hash drift: {path}")


def _root_relative(root: Path, path: Path) -> str:
    try:
        return (
            path.resolve(strict=False).relative_to(root.resolve(strict=True)).as_posix()
        )
    except ValueError as exc:
        raise CvrpF1Error(f"F1 path escapes output root: {path}") from exc


def _canonical_pretty_bytes(payload: Mapping[str, Any]) -> bytes:
    return (
        json.dumps(
            payload, indent=2, sort_keys=True, ensure_ascii=True, allow_nan=False
        )
        + "\n"
    ).encode("utf-8")


def _canonical_sha256(payload: Any) -> str:
    raw = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("utf-8")
    return _sha256_bytes(raw)


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _object(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        raise CvrpF1Error(f"F1 {label} must be an object")
    return dict(value)


def _object_or_empty(value: Any) -> dict[str, Any]:
    return dict(value) if isinstance(value, Mapping) else {}


def _list(payload: Mapping[str, Any], key: str) -> list[Any]:
    value = payload.get(key)
    if not isinstance(value, list):
        raise CvrpF1Error(f"F1 {key} must be a list")
    return value


def _typed(value: Any) -> dict[str, Any]:
    if value is None:
        return _missing("solver_did_not_emit")
    return {"status": "present", "value": value}


def _missing(reason: str) -> dict[str, str]:
    return {"status": "missing", "reason": reason}
