"""Runtime sealing and identity probes for the CVRP F1 ancestry matrix."""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
from typing import Any, Mapping, Sequence

from scion.problems.cvrp.evidence.f1_contract import (
    CvrpF1Error,
    F1_DESIGN_SHA256,
    F1_RUNTIME_COMMIT,
    F1_SELECTED_SURFACE,
    _GENERATED_SUFFIXES,
)
from scion.problems.cvrp.evidence.f1_io import (
    _canonical_sha256,
    _list,
    _object,
    _require_hash,
    _safe_source_file,
    _sha256_bytes,
    _sha256_file,
    _write_exclusive,
)


def git_package_inventory(repo: Path) -> tuple[tuple[str, str], ...]:
    completed = subprocess.run(
        [
            "git",
            "ls-tree",
            "-r",
            "--full-tree",
            F1_RUNTIME_COMMIT,
            "scion/scion",
        ],
        cwd=str(repo),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise CvrpF1Error(f"F1 runtime git commit is unavailable: {completed.stderr}")
    rows: list[tuple[str, str]] = []
    prefix = "scion/scion/"
    for line in completed.stdout.splitlines():
        meta, path = line.split("\t", 1)
        mode, kind, blob = meta.split()
        if kind != "blob" or mode not in {"100644", "100755"}:
            raise CvrpF1Error(f"F1 git source closure has unsupported entry: {path}")
        if not path.startswith(prefix):
            raise CvrpF1Error("F1 git source path prefix drift")
        relative = path[len(prefix) :]
        parts = Path(relative).parts
        if not parts or parts[0] == "tests":
            continue
        if len(parts) >= 2 and parts[0] == "problems" and parts[1] == "cvrp":
            continue
        if "__pycache__" in parts or Path(relative).suffix in _GENERATED_SUFFIXES:
            raise CvrpF1Error("F1 runtime git closure contains generated bytecode")
        rows.append((relative, blob))
    if not rows:
        raise CvrpF1Error("F1 runtime git package closure is empty")
    return tuple(sorted(rows))


def copy_git_inventory(
    repo: Path, inventory: Sequence[tuple[str, str]], target: Path
) -> None:
    for relative, blob in inventory:
        completed = subprocess.run(
            ["git", "cat-file", "blob", blob],
            cwd=str(repo),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if completed.returncode != 0:
            raise CvrpF1Error(f"F1 cannot read git blob {blob}: {relative}")
        identity = hashlib.sha1(
            b"blob " + str(len(completed.stdout)).encode() + b"\0" + completed.stdout
        ).hexdigest()
        if identity != blob:
            raise CvrpF1Error(f"F1 git blob identity drift: {relative}")
        _write_exclusive(target / relative, completed.stdout)


def verify_editable_identity(
    root: Path, manifest: Mapping[str, Any], expected: str
) -> None:
    if editable_hash(root, manifest) != expected:
        raise CvrpF1Error("F1 champion editable hash reproduction failed")
    for raw in _list(manifest, "files"):
        row = _object(raw, "editable file")
        _require_hash(root / str(row["file_path"]), str(row["sha256"]), "editable file")


def editable_hash(root: Path, manifest: Mapping[str, Any]) -> str:
    digest = hashlib.sha256()
    for raw in _list(manifest, "files"):
        row = _object(raw, "editable identity file")
        relative = str(row["file_path"])
        content = _safe_source_file(root, Path(relative)).read_bytes()
        digest.update(relative.encode())
        digest.update(content)
    return digest.hexdigest()


def import_probe(
    *,
    python: str,
    package_root: Path,
    workspace: Path,
    data_root: Path | None,
    case_paths: Sequence[str],
    dependency_paths: Sequence[str],
    expected_runtime_identity: str,
) -> Mapping[str, Any]:
    script = r"""
import hashlib, json, os, platform, random, sys
from pathlib import Path
def _inside(path, root):
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False
import scion
from scion.problems.cvrp import solver
from scion.problems.cvrp.cvrplib import load_cvrplib_instance
from scion.problems.cvrp.policies import baseline_algorithm
from scion.problems.cvrp.solution_checks import (
    check_feasibility,
    check_solution_consistency,
    deserialize_solver_output,
)

package_root = Path(os.environ["F1_PACKAGE_ROOT"]).resolve()
package = package_root
def inventory():
    rows=[]
    for path in sorted(package.rglob("*"), key=lambda p:p.as_posix()):
        if path.is_symlink():
            raise SystemExit(f"symlink in package: {path}")
        if path.is_file():
            relative=path.relative_to(package).as_posix()
            if "__pycache__" in Path(relative).parts or path.suffix in {".pyc",".pyo"}:
                raise SystemExit(f"generated bytecode in package: {relative}")
            rows.append({"path":relative,"sha256":hashlib.sha256(path.read_bytes()).hexdigest()})
    raw=json.dumps(rows,sort_keys=True,separators=(",",":"),allow_nan=False).encode()
    return hashlib.sha256(raw).hexdigest()
case_facts=[]
data_root=os.environ.get("F1_DATA_ROOT","")
for relative in json.loads(os.environ["F1_CASE_PATHS_JSON"]):
    instance=load_cvrplib_instance(Path(data_root)/relative)
    smoke_solution=solver.solve(instance, random.Random(0))
    route_count=len(smoke_solution.routes)
    allowed_routes=instance.allowed_routes
    if allowed_routes is None:
        allowed_routes=instance.bks_routes
    fleet_violation=max(0, route_count-allowed_routes) if allowed_routes is not None else 0
    total_distance=sum(instance.route_distance(route) for route in smoke_solution.routes)
    smoke_artifact=deserialize_solver_output(
        {
            "routes":[list(route) for route in smoke_solution.routes],
            "feasible":True,
            "objective":{
                "fleet_violation":fleet_violation,
                "total_distance":total_distance,
                "routes":route_count,
            },
        },
        instance,
    )
    consistency=check_solution_consistency(smoke_artifact, instance)
    feasibility=check_feasibility(smoke_artifact, instance)
    if not consistency.passed or not feasibility.passed:
        raise SystemExit(f"solution-validity smoke failed: {relative}")
    case_facts.append({
        "case_path": relative,
        "name": instance.name,
        "dimension": len(instance.nodes),
        "capacity": instance.capacity,
        "bks": instance.bks,
        "bks_routes": instance.bks_routes,
        "allowed_routes": instance.allowed_routes,
        "use_integer_cost": instance.use_integer_cost,
        "solution_validity_smoke":{
            "consistency_passed":consistency.passed,
            "feasibility_passed":feasibility.passed,
            "route_count":route_count,
            "fleet_violation":fleet_violation,
            "total_distance":total_distance,
        },
    })
dependency_roots=[Path(value).resolve() for value in json.loads(os.environ["F1_DEPENDENCY_PATHS_JSON"])]
dependency_modules=[]
for name,module in sorted(sys.modules.items()):
    raw_path=getattr(module,"__file__",None)
    if not raw_path:
        continue
    path=Path(raw_path).resolve()
    if not path.is_file():
        continue
    try:
        path.relative_to(package_root)
    except ValueError:
        pass
    else:
        continue
    if not any(_inside(path, root) for root in dependency_roots):
        continue
    dependency_modules.append({"module":name,"file":str(path),"sha256":hashlib.sha256(path.read_bytes()).hexdigest()})
native=[]
maps=Path("/proc/self/maps")
if maps.is_file():
    paths=set()
    for line in maps.read_text(encoding="utf-8").splitlines():
        tail=line.split(maxsplit=5)
        if len(tail)==6 and tail[5].startswith("/"):
            path=Path(tail[5]).resolve()
            if path.is_file() and (".so" in path.name or "ld-linux" in path.name):
                paths.add(path)
    native=[{"file":str(path),"sha256":hashlib.sha256(path.read_bytes()).hexdigest()} for path in sorted(paths)]
payload={
    "python_executable_path":str(Path(sys.executable).resolve()),
    "python_version":sys.version,
    "platform":platform.platform(),
    "sys_path":[str(Path(value).resolve()) if value else "" for value in sys.path],
    "scion_locations":[str(Path(value).resolve()) for value in scion.__path__],
    "solver_file":str(Path(solver.__file__).resolve()),
    "baseline_algorithm_file":str(Path(baseline_algorithm.__file__).resolve()),
    "runtime_identity_sha256":inventory(),
    "dependency_modules":dependency_modules,
    "native_libraries":native,
    "case_facts":case_facts,
}
if payload["runtime_identity_sha256"] != os.environ["F1_EXPECTED_RUNTIME_IDENTITY"]:
    raise SystemExit("runtime identity mismatch")
print(json.dumps(payload,sort_keys=True,separators=(",",":"),allow_nan=False))
"""
    env = child_environment(
        package_root=package_root,
        dependency_paths=dependency_paths,
        data_root=data_root,
    )
    env["F1_PACKAGE_ROOT"] = str(package_root)
    env["F1_CASE_PATHS_JSON"] = json.dumps(list(case_paths), separators=(",", ":"))
    env["F1_DEPENDENCY_PATHS_JSON"] = json.dumps(
        list(dependency_paths), separators=(",", ":")
    )
    env["F1_EXPECTED_RUNTIME_IDENTITY"] = expected_runtime_identity
    if data_root is not None:
        env["F1_DATA_ROOT"] = str(data_root)
    completed = subprocess.run(
        [python, "-S", "-c", script],
        cwd=str(workspace),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise CvrpF1Error(
            "F1 sealed import probe failed: "
            + completed.stderr.decode("utf-8", errors="replace")
        )
    payload = json.loads(completed.stdout)
    if not isinstance(payload, dict):
        raise CvrpF1Error("F1 import probe returned non-object")
    return payload


def python_identity(value: str | Path) -> dict[str, Any]:
    candidate = shutil.which(str(value)) or str(Path(value).expanduser())
    executable = Path(candidate).resolve(strict=True)
    if not executable.is_file() or not os.access(executable, os.X_OK):
        raise CvrpF1Error(f"F1 Python executable is invalid: {executable}")
    script = (
        "import json,platform,sys; "
        "print(json.dumps({'version':sys.version,'version_info':list(sys.version_info),"
        "'implementation':sys.implementation.name,'cache_tag':sys.implementation.cache_tag,"
        "'compiler':platform.python_compiler(),'build':list(platform.python_build()),"
        "'platform':platform.platform(),'executable_path':sys.executable},"
        "sort_keys=True,separators=(',',':')))"
    )
    completed = subprocess.run(
        [str(executable), "-S", "-c", script],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise CvrpF1Error("F1 cannot inspect Python build")
    build = json.loads(completed.stdout)
    if build["executable_path"] != str(executable):
        raise CvrpF1Error("F1 Python realpath drift")
    executable_sha = _sha256_file(executable)
    return {
        "executable_path": str(executable),
        "executable_sha256": executable_sha,
        "build_identity": build,
        "runtime_identity_sha256": _canonical_sha256(
            {
                "schema": "scion.cvrp_f1_python_runtime.v1",
                "executable_sha256": executable_sha,
                "build_identity": build,
            }
        ),
    }


def dependency_paths(python: str) -> tuple[str, ...]:
    script = (
        "import json,site; "
        "print(json.dumps([p for p in site.getsitepackages() if p]))"
    )
    env = {"PYTHONNOUSERSITE": "1", "LC_ALL": "C.UTF-8", "LANG": "C.UTF-8"}
    completed = subprocess.run(
        [python, "-c", script],
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        raise CvrpF1Error("F1 cannot discover system dependency paths")
    paths: list[str] = []
    for value in json.loads(completed.stdout):
        path = Path(value).resolve(strict=True)
        if not path.is_dir():
            continue
        text = str(path)
        if text not in paths:
            paths.append(text)
    if not paths:
        raise CvrpF1Error("F1 found no system dependency path")
    return tuple(paths)


def child_environment(
    *,
    package_root: Path | None,
    dependency_paths: Sequence[str],
    data_root: Path | None,
) -> dict[str, str]:
    env = {
        "PYTHONDONTWRITEBYTECODE": "1",
        "PYTHONNOUSERSITE": "1",
        "PYTHONHASHSEED": "0",
        "LC_ALL": "C.UTF-8",
        "LANG": "C.UTF-8",
        "TZ": "UTC",
        "SCION_SELECTED_SURFACE": F1_SELECTED_SURFACE,
    }
    entries = ([] if package_root is None else [str(package_root)]) + list(
        dependency_paths
    )
    if entries:
        env["PYTHONPATH"] = os.pathsep.join(entries)
    if data_root is not None:
        env["SCION_PROBLEM_DATA_ROOT"] = str(data_root)
    return env


def git_context(repo: Path, design: Path) -> dict[str, Any]:
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if head.returncode != 0:
        raise CvrpF1Error("F1 repository git context is unavailable")
    commit = head.stdout.strip()
    relative = design.relative_to(repo).as_posix()
    shown = subprocess.run(
        ["git", "show", f"{commit}:{relative}"],
        cwd=str(repo),
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    tracked = shown.returncode == 0 and _sha256_bytes(shown.stdout) == F1_DESIGN_SHA256
    return {"git_commit_context": commit, "tracked_at_git_commit": tracked}


def implementation_source_identities(repo: Path) -> list[dict[str, Any]]:
    paths = (
        "scion/scion/problems/cvrp/evidence/f1_ancestry.py",
        "scion/scion/problems/cvrp/evidence/f1_contract.py",
        "scion/scion/problems/cvrp/evidence/f1_io.py",
        "scion/scion/problems/cvrp/evidence/f1_materialization.py",
        "scion/scion/problems/cvrp/evidence/f1_runtime.py",
        "scion/scion/problems/cvrp/evidence/f1_preparation.py",
        "scion/scion/problems/cvrp/evidence/f1_runner.py",
        "scion/scion/problems/cvrp/evidence/f1_analysis.py",
        "scion/tools/cvrp_f1_ancestry.py",
        "scion/scion/protocol/stats.py",
    )
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(repo),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if head.returncode != 0:
        raise CvrpF1Error("F1 implementation git context is unavailable")
    commit = head.stdout.strip()
    rows = []
    for relative in paths:
        path = repo / relative
        if not path.is_file() or path.is_symlink():
            raise CvrpF1Error(f"F1 implementation source is missing: {relative}")
        sha256 = _sha256_file(path)
        shown = subprocess.run(
            ["git", "show", f"{commit}:{relative}"],
            cwd=str(repo),
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        rows.append(
            {
                "path": relative,
                "sha256": sha256,
                "tracked_at_git_commit": (
                    shown.returncode == 0 and _sha256_bytes(shown.stdout) == sha256
                ),
            }
        )
    return rows


__all__ = [
    "child_environment",
    "copy_git_inventory",
    "dependency_paths",
    "editable_hash",
    "git_context",
    "git_package_inventory",
    "implementation_source_identities",
    "import_probe",
    "python_identity",
    "verify_editable_identity",
]
