"""Default parameters for the branch-owned CVRP solver-design algorithm."""
from __future__ import annotations

ENABLE_BASELINE_ALGORITHM = True

SIGMA_BEST = 33.0
SIGMA_BETTER = 9.0
SIGMA_ACCEPTED = 13.0

BASELINE_TIME_FRACTION = 0.80
DESTROY_RATIO = (0.10, 0.40)
SEGMENT_LENGTH = 100
REACTION_FACTOR = 0.1
VNS_MAX_NO_IMPROVE = 5000
USE_VNS = True
CW_THRESHOLD = 1500
VNS_THRESHOLD = 1200
ALNS_THRESHOLD = 2000
MAX_DESTROY_CUSTOMERS = 200
EXIT_RESERVE_FRACTION = 0.03

_EPS = 1e-9
