"""Compatibility facade for proposal preview tools.

The implementation is split under ``scion.proposal.tools.previews``; this module
keeps the historical import path stable.
"""

from __future__ import annotations

from scion.proposal.tools.models import (
    AlgorithmSmokeInput,
    ContractPreviewInput,
    DraftHypothesisInput,
    DraftPatchInput,
    InterfacePreviewInput,
    SchemaPreviewInput,
    TargetPermissionPreviewInput,
)
from scion.proposal.tools.previews.algorithm_smoke import *
from scion.proposal.tools.previews.algorithm_smoke_feedback import (
    _algorithm_smoke_agent_payload,
    compact_algorithm_smoke_observation_for_agent,
)
from scion.proposal.tools.previews.common import *
from scion.proposal.tools.previews.contract import *
from scion.proposal.tools.previews.permissions import *
from scion.proposal.tools.previews.schema import *
from scion.proposal.tools.previews.telemetry_static import *

__all__ = [
    "AlgorithmSmokeInput",
    "AlgorithmSmokeTool",
    "ContractPreviewInput",
    "ContractPreviewTool",
    "DraftHypothesisInput",
    "DraftHypothesisTool",
    "DraftPatchInput",
    "DraftPatchTool",
    "InterfacePreviewInput",
    "InterfacePreviewTool",
    "SchemaPreviewInput",
    "SchemaPreviewTool",
    "TargetPermissionPreviewInput",
    "TargetPermissionPreviewTool",
    "compact_algorithm_smoke_observation_for_agent",
    "_ALGORITHM_SMOKE_DEFAULT_SEED",
    "_ALGORITHM_SMOKE_LOW_EFFORT_MAX_ATTEMPTS",
    "_ALGORITHM_SMOKE_LOW_EFFORT_MAX_ITERATIONS",
    "_ALGORITHM_SMOKE_LOW_EFFORT_MAX_RUNTIME_RATIO",
    "_ALGORITHM_SMOKE_LOW_EFFORT_MIN_CASES",
    "_ALGORITHM_SMOKE_LOW_EFFORT_STOP_REASONS",
    "_ALGORITHM_SMOKE_MAX_SCREENING_CASES",
    "_ALGORITHM_SMOKE_TIMEOUT_SEC",
    "_ALGORITHM_SMOKE_TIME_LIMIT_SEC",
    "_NONEMPTY_SEQUENCE_NOVELTY_FIELDS",
    "_PREVIEW_CHECK_DETAIL_CHARS",
    "_PREVIEW_FAILURE_REASON_CHARS",
    "_PREVIEW_MAX_CHECKS",
    "_PREVIEW_PROBLEM_ISSUE_CHARS",
    "_PREVIEW_PROBLEM_MAX_CHECKS",
    "_RuntimeSmokeCase",
    "_SEMANTIC_SIGNATURE_SCALAR_STRING_CHARS",
    "_active_boundary_novelty_requirements",
    "_active_problem_boundary_constraint_payload",
    "_active_problem_boundary_violation",
    "_algorithm_smoke_agent_payload",
    "_apply_file_change_to_runtime_smoke_workspace",
    "_apply_patch_to_runtime_smoke_workspace",
    "_artifact_id",
    "_champion_version",
    "_checks_payload",
    "_combined_patch_code_for_mechanism",
    "_compact_preview_value",
    "_compact_problem_preview",
    "_compact_problem_preview_checks",
    "_compact_runtime_audit_failure",
    "_compact_runtime_smoke_payload",
    "_compact_solver_design_micro_benchmark",
    "_compare_solver_design_raw_outputs",
    "_contract_gate",
    "_contract_preview_issue_strings",
    "_contract_preview_issue_summary",
    "_contract_problem_spec",
    "_contract_result_payload",
    "_contract_summary_payload",
    "_drop_internal_preview_objects",
    "_ensure_runtime_smoke_path_writable",
    "_expected_telemetry_contract_preview",
    "_first_failure",
    "_first_int",
    "_float_or_none",
    "_forced_action_target_violation",
    "_forced_hypothesis_violation",
    "_forced_surface_constraint_payload",
    "_hypothesis_from_input",
    "_hypothesis_preview_summary",
    "_hypothesis_schema_preview",
    "_hypothesis_selected_surface",
    "_is_nonempty_text_sequence",
    "_is_solver_design_runtime_patch_path",
    "_load_runtime_smoke_yaml",
    "_mechanism_binding_preview",
    "_mechanism_telemetry_static_preview",
    "_module_classes",
    "_module_level_functions",
    "_nonnegative_int",
    "_operator_execute_signature",
    "_patch_file_change_preview_summary",
    "_patch_from_input",
    "_patch_path_error",
    "_patch_preview_summary",
    "_patch_records_mechanism_call",
    "_preview_max_checks_for_patch",
    "_problem_preview_issues",
    "_problem_spec_for_runtime_audit",
    "_problem_surface_preview",
    "_resolve_smoke_instance_path",
    "_run_solver_design_smoke",
    "_runtime_algorithm_smoke_preview",
    "_runtime_smoke_audit_failure",
    "_runtime_smoke_base_workspace",
    "_runtime_smoke_cases",
    "_runtime_smoke_stage_arguments",
    "_runtime_smoke_stage_value",
    "_runtime_stop_reason",
    "_schema_preview_hypothesis_payload",
    "_schema_preview_patch_payload",
    "_schema_preview_summary",
    "_select_runtime_smoke_screening_cases",
    "_semantic_signature_preview_guidance",
    "_semantic_signature_value_missing",
    "_solver_design_low_effort_issue",
    "_solver_design_micro_benchmark_issue",
    "_solver_design_micro_benchmark_result",
    "_solver_design_patch_claims_search_effort",
    "_solver_design_patch_paths",
    "_solver_design_smoke_repair_guidance",
    "_solver_design_smoke_runtime_underspent",
    "_solver_design_zero_effort_issue",
    "_solver_run_failure_detail",
    "_string_list",
]
