"""Shared constants for the CVRP solver runtime facade and helpers."""

_OBJECTIVE_TOLERANCE = 1e-9
_MAIN_SEARCH_EXIT_RESERVE_SEC = 0.75
_ROUTE_POOL_EXIT_RESERVE_SEC = 2.50
_MAX_EXIT_RESERVE_FRACTION = 0.15

__all__ = [
    "_MAX_EXIT_RESERVE_FRACTION",
    "_MAIN_SEARCH_EXIT_RESERVE_SEC",
    "_OBJECTIVE_TOLERANCE",
    "_ROUTE_POOL_EXIT_RESERVE_SEC",
]
