"""CVRP-owned proposal quality contracts."""
from __future__ import annotations

from scion.problems.cvrp.proposal_quality.hypothesis_contract import (
    CVRP_CONSTRUCTION_SEED_DIRECT_EFFECT_FAILURE,
    CVRP_REVIEWED_DEFAULT_AVOID_FAILURE,
    CVRP_REVIEWED_DEFAULT_AVOID_MECHANISMS,
    CVRP_SOLVER_DESIGN_STATIC_QUALITY_FAILURE,
    CVRP_SUCCESSOR37_DEFAULT_AVOID_FAILURE,
    CVRP_SUCCESSOR37_DEFAULT_AVOID_MECHANISMS,
    validate_cvrp_hypothesis_quality,
)

__all__ = [
    "CVRP_CONSTRUCTION_SEED_DIRECT_EFFECT_FAILURE",
    "CVRP_REVIEWED_DEFAULT_AVOID_FAILURE",
    "CVRP_REVIEWED_DEFAULT_AVOID_MECHANISMS",
    "CVRP_SOLVER_DESIGN_STATIC_QUALITY_FAILURE",
    "CVRP_SUCCESSOR37_DEFAULT_AVOID_FAILURE",
    "CVRP_SUCCESSOR37_DEFAULT_AVOID_MECHANISMS",
    "validate_cvrp_hypothesis_quality",
]
