"""Problem-neutral research guidance contract surface."""

from scion.research_guidance.rendering import (
    RenderedResearchGuidance,
    render_research_guidance_contract,
)
from scion.research_guidance.manifest import (
    LEGACY_RESEARCH_FOCUS_ADAPTER_SCHEMA,
    RESEARCH_GUIDANCE_CONTRACT_MANIFEST_KEY,
    RESEARCH_GUIDANCE_PROMPT_SCHEMA,
    launch_research_guidance_payload,
    legacy_research_focus_to_contract,
    render_prepared_research_guidance_from_manifest,
    research_guidance_contract_from_dict,
    research_guidance_contract_from_manifest,
    research_guidance_contract_to_dict,
    research_guidance_projection_summary,
)
from scion.research_guidance.schema import (
    AvoidRule,
    ContinuityRequirement,
    EvidenceRequirement,
    GuidanceBlock,
    GuidanceContext,
    GuidanceVisibility,
    MeasurementGuidanceSummary,
    ProblemResearchGuidanceProvider,
    RequiredMechanism,
    ResearchGuidanceContract,
    ResearchGuidanceValidationError,
    collect_research_guidance_errors,
    expected_research_guidance_rendered_paths,
    validate_research_guidance_contract,
    validate_research_guidance_rendered_paths,
)

__all__ = [
    "AvoidRule",
    "ContinuityRequirement",
    "EvidenceRequirement",
    "GuidanceBlock",
    "GuidanceContext",
    "GuidanceVisibility",
    "MeasurementGuidanceSummary",
    "ProblemResearchGuidanceProvider",
    "LEGACY_RESEARCH_FOCUS_ADAPTER_SCHEMA",
    "RESEARCH_GUIDANCE_CONTRACT_MANIFEST_KEY",
    "RESEARCH_GUIDANCE_PROMPT_SCHEMA",
    "RenderedResearchGuidance",
    "RequiredMechanism",
    "ResearchGuidanceContract",
    "ResearchGuidanceValidationError",
    "collect_research_guidance_errors",
    "expected_research_guidance_rendered_paths",
    "launch_research_guidance_payload",
    "legacy_research_focus_to_contract",
    "render_prepared_research_guidance_from_manifest",
    "render_research_guidance_contract",
    "research_guidance_contract_from_dict",
    "research_guidance_contract_from_manifest",
    "research_guidance_contract_to_dict",
    "research_guidance_projection_summary",
    "validate_research_guidance_contract",
    "validate_research_guidance_rendered_paths",
]
